# Generated by Django 4.2.20 on 2025-04-23 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rabble", "0002_allmodels"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
