# Generated by Django 5.1.7 on 2025-04-24 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rabble", "0003_user_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="subrabbles",
            name="identifier",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
